version: Compose specification
services:
    homeassistant:
        image: "ghcr.io/home-assistant/home-assistant"
        privileged: true
        network_mode: host
        restart: always
        volumes:
            - /opt/homeassistant/:/config
            - /etc/localtime:/etc/localtime:ro
    nginx:
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        restart: always
        depends_on:
            - homeassistant
        volumes:
            - ./conf.d/:/etc/nginx/conf.d/
            - ./nginx.conf:/etc/nginx/nginx.conf
