version: Compose specification
services:
    assistant:
        image: "ghcr.io/home-assistant/home-assistant"
        privileged: true
        network_mode: host
        restart: unless-stopped
        volumes:
            - config:/config
            - /etc/localtime:/etc/localtime:ro
volumes:
    config:
