services:
    portainer:
        image: portainer/portainer-ce
        command: -H unix:///var/run/docker.sock
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        expose:
            - 8000
            - 9000
        networks:
            - traefik-net

volumes:
    portainer_data:

networks:
    traefik-net:
        external: true
