### Static Configuration
log:
    level: INFO
api:
    dashboard: true
providers:
    file:
        directory: /etc/traefik/dynamic-conf
        watch: true
entryPoints:
    web:
        address: :80
        http:
            redirections:
                entryPoint:
                    to: websecure
                    scheme: https
                    permanent: true
    websecure:
        address: :443
    metrics:
        address: :8082
metrics:
    prometheus:
        entryPoint: metrics
