### Static Configuration
log:
    level: INFO
api:
    dashboard: true
providers:
    file:
        directory: /etc/traefik/dynamic-conf
        watch: true
entryPoints:
    web:
        address: :80
        http:
            redirections:
                entryPoint:
                    to: websecure
    websecure:
        address: :443
        http3: {}
    metrics:
        address: :8082
metrics:
    prometheus:
        entryPoint: metrics
        manualRouting: true
