version: Compose specification

services:
    uptime-kuma:
        image: louislam/uptime-kuma
        restart: always
        volumes:
            - uptime-kuma-data:/app/data
        networks:
            - traefik-net

networks:
    traefik-net:
        external: true

volumes:
    uptime-kuma-data:
