version: '3'
services:
    redis:
        image: redislabs/redismod
        ports:
            - "6379:6379"
        volumes:
            - /opt/redis/data:/data
        restart: always
    redisinsight:
        image: redislabs/redisinsight
        ports:
            - "8001:8001"
        volumes:
            - redisinsight_db:/db
        restart: always
volumes:
    redisinsight_db:
