version: '3'
services:
    redis:
        image: redislabs/redismod
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
    redisinsight:
        image: redislabs/redisinsight
        ports:
            - "8001:8001"
        volumes:
            - redisinsight_db:/db
volumes:
    redis_data:
    redisinsight_db:
