http:
    routers:
        frontend:
            rule: Host(`portainer.x.io`)
            service: frontend
        edge:
            rule: Host(`edge.x.io`)
            service: edge
    services:
        frontend:
            loadBalancer:
                servers:
                    -   url: "http://portainer:9000"
        edge:
            loadBalancer:
                servers:
                    -   url: "http://portainer:8000"
