version: Compose specification

services:
    ldap:
        image: osixia/openldap
        ports:
            - "389:389"
            - "636:636"
        restart: always
        environment:
            - LDAP_ADMIN_PASSWORD=secret
        volumes:
            - ldap:/var/lib/ldap
            - slapd:/etc/ldap/slapd.d
        networks:
            - traefik-net

    ldapadmin:
        image: osixia/phpldapadmin
        restart: always
        ports:
            - 6443:443
        environment:
            - PHPLDAPADMIN_LDAP_HOSTS=ldap
        networks:
            - traefik-net
volumes:
    ldap:
    slapd:

networks:
    traefik-net:
        external: true
