version: Compose specification

services:
    ldap:
        image: osixia/openldap
        restart: always
        environment:
            - LDAP_ADMIN_PASSWORD=secret
        volumes:
            - ldap:/var/lib/ldap
            - slapd:/etc/ldap/slapd.d
        networks:
            - traefik-net

    ldapadmin:
        image: osixia/phpldapadmin
        restart: always
        environment:
            - PHPLDAPADMIN_LDAP_HOSTS=ldap
            # if configure https by traefik, you need to configure the following two lines
            # if not, remove them
            - VIRTUAL_HOST=ldap.m.local
            - PHPLDAPADMIN_HTTPS=false
        networks:
            - traefik-net
volumes:
    ldap:
    slapd:

networks:
    traefik-net:
        external: true
