services:
    ldap-srv:
        image: bitnami/openldap
        restart: always
        environment:
            - LDAP_ROOT=dc=chaos,dc=io
            - LDAP_ADMIN_USERNAME=admin
            - LDAP_ADMIN_PASSWORD=secret
            - LDAP_USERS=user01,user02
            - LDAP_PASSWORDS=password1,password2
        volumes:
            - openldap:/bitnami/openldap
        networks:
            - traefik-net

    ldap-ui:
        image: osixia/phpldapadmin
        restart: always
        environment:
            # due to bitnami/openldap use port 1389 and 1636, so we need to change the port to 1389
            PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'ldap-srv': [{'server': [{'port': 1389}]}]}]"
            # if configure https by traefik, you need to configure the following two lines
            # if not, remove them
            VIRTUAL_HOST: ldap.x.internal
            PHPLDAPADMIN_HTTPS: false
        networks:
            - traefik-net
volumes:
    openldap:

networks:
    traefik-net:
        external: true
