version: Compose specification

services:
    ldap:
        image: osixia/openldap
        restart: always
        environment:
            - LDAP_ORGANISATION=Aurora Inc.
            # if LDAP_DOMAIN=yoooo.fun, the login DN will be "cn=admin,dc=yoooo,dc=fun"
            # LDAP_DOMAIN default value is "example.org"
            # so default login DN is "cn=admin,dc=example,dc=org"
            - LDAP_DOMAIN=yoooo.fun
            - LDAP_ADMIN_PASSWORD=secret
        volumes:
            - ldap:/var/lib/ldap
            - slapd:/etc/ldap/slapd.d
        networks:
            - traefik-net

    ldapadmin:
        image: osixia/phpldapadmin
        restart: always
        environment:
            - PHPLDAPADMIN_LDAP_HOSTS=ldap
            # if configure https by traefik, you need to configure the following two lines
            # if not, remove them
            - VIRTUAL_HOST=ldap.m.local
            - PHPLDAPADMIN_HTTPS=false
        networks:
            - traefik-net
volumes:
    ldap:
    slapd:

networks:
    traefik-net:
        external: true
