http:
    routers:
        ldap:
            rule: "Host(`ldap.x.internal`)"
            service: "ldap"
            tls: { }
        ssp:
            rule: "Host(`ssp.x.internal`)"
            service: "ssp"
            tls: { }

    services:
        ldap:
            loadBalancer:
                servers:
                    -   url: "http://ldap-ui"
        ssp:
            loadBalancer:
                servers:
                    -   url: "http://ssp"
