http:
    routers:
        prom:
            rule: "Host(`prometheus.x.internal`)"
            service: "prom"
            tls: { }

    services:
        prom:
            loadBalancer:
                servers:
                    -   url: "http://prometheus:9090"
