### Dynamic Configuration
tls:
    certificates:
        -   certFile: /certs/cert.pem
            keyFile: /certs/key.pem
http:
    routers:
        dashboard:
            rule: Host(`traefik.x.internal`)
            service: api@internal
            tls: { }
# metrics router is not necessary, but it's a good practice to separate metrics from other services.
        metrics:
            rule: Host(`traefik.x.internal`) && PathPrefix(`/metrics`)
            service: metrics
            tls: { }
    services:
        metrics:
            loadBalancer:
                servers:
                    -   url: http://traefik:8082
