### Dynamic Configuration
tls:
    certificates:
        -   certFile: /certs/cert.pem
            keyFile: /certs/key.pem
            stores:
                - default
    # Specifying the default certificate
    stores:
        default:
            defaultCertificate:
                certFile: /certs/cert.pem
                keyFile: /certs/key.pem
http:
    routers:
        dashboard:
            rule: Host(`traefik.m.local`)
            service: api@internal
            tls: { }
