version: '3.8'

services:
    gerrit:
        image: gerritcodereview/gerrit
        user: root
        ports:
            - "29418:29418"
        expose:
            - 8080
        depends_on:
            - ldap
        volumes:
            - /opt/gerrit/etc:/var/gerrit/etc
            - /opt/gerrit/git:/var/gerrit/git
            - /opt/gerrit/db:/var/gerrit/db
            - /opt/gerrit/index:/var/gerrit/index
            - /opt/gerrit/cache:/var/gerrit/cache
            - /opt/gerrit/plugins:/var/gerrit/plugins
        environment:
            - CANONICAL_WEB_URL=http://gerrit.m.local
            - HTTPD_LISTEN_URL=proxy-http://*:8080
        networks:
            - traefik-net
        command: init

    ldap:
        image: osixia/openldap
        ports:
            - "389:389"
            - "636:636"
        restart: always
        environment:
            - LDAP_ADMIN_PASSWORD=secret
        volumes:
            - /opt/gerrit/ldap/var:/var/lib/ldap
            - /opt/gerrit/ldap/etc:/etc/ldap/slapd.d
        networks:
            - traefik-net

    ldapadmin:
        image: osixia/phpldapadmin
        ports:
            - "6443:443"
        restart: always
        environment:
            - PHPLDAPADMIN_LDAP_HOSTS=ldap
        networks:
            - traefik-net

networks:
    traefik-net:
        external: true
