version: '3.8'
services:
    jenkins:
        image: jenkins/jenkins
        container_name: jenkins
        privileged: true
        user: root
        ports:
            - "8080:8080"
            - "50000:50000"
        restart: always
        volumes:
            - /opt/jenkins:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
