version: '3.8'
services:
    jenkins:
        image: jenkins/jenkins
        container_name: jenkins
        privileged: true
        user: root
        expose:
            - 8080
            - 50000
        restart: always
        extra_hosts:
            # config for gerrit, sonar, ldap. if no, remove them
            - gerrit.m.local:192.168.91.103
            - sonar.m.local:192.168.91.103
            - ldap.m.local:192.168.91.103
        volumes:
            - jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - TZ=Asia/Shanghai
        networks:
            - traefik-net

volumes:
    jenkins_home:

networks:
    traefik-net:
        external: true
