version: Compose specification

services:
    grafana:
        image: grafana/grafana
        restart: always
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - "./grafana.ini:/etc/grafana/grafana.ini"
            - "./provisioning:/etc/grafana/provisioning"
            - "grafana-data:/var/lib/grafana"
        networks:
            - traefik-net
networks:
    traefik-net:
        external: true
volumes:
    grafana-data:
