### Static Configuration
log:
    level: DEBUG
api:
    insecure: true
    dashboard: true
entryPoints:
    web:
        address: :80
providers:
    docker:
        exposedByDefault: false
    file:
        # location in traefik container
        # filename: /traefik.yml
        directory: /etc/traefik/dynamic-conf
