### Static Configuration
log:
    level: INFO
api:
    insecure: true
    dashboard: true
entryPoints:
    web:
        address: :80
providers:
    file:
        # location in traefik container
        # filename: /traefik.yml
        directory: /etc/traefik/dynamic-conf
        watch: true
