apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    finalizers:
        - kubernetes.io/pvc-protection
    name: homeassistant
    namespace: default
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 10Gi
    storageClassName: 外挂存储的名字
    volumeMode: Filesystem

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: homeassistant
spec:
    replicas: 1
    selector:
        matchLabels:
            app: homeassistant
    template:
        metadata:
            labels:
                app: homeassistant
        spec:
            containers:
                -   name: homeassistant
                    image: homeassistant/home-assistant
                    ports:
                        -   containerPort: 8123
                    resources:
                        limits:
                            cpu: 200m
                            memory: 512Mi
                        requests:
                            cpu: 10m
                            memory: 64Mi
                    volumeMounts:
                        -   mountPath: /config
                            name: data
            volumes:
                -   name: data
                    persistentVolumeClaim:
                        claimName: homeassistant

---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: homeassistant
    name: homeassistant
spec:
    externalTrafficPolicy: Cluster
    ports:
        -   protocol: TCP
            port: 8123
            targetPort: 8123
    selector:
        app: homeassistant
    sessionAffinity: None
    type: NodePort
